blank_issues_enabled: false
contact_links:
  - name: Feature request/新特性请求
    url: https://github.com/Pik-4/HsMod/discussions/categories/ideas-%E8%AE%B8%E6%84%BF%E6%B1%A0
    about: Suggest an idea./提出建议
